WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT = _{
  "/*" ~ (!"*/" ~ ANY)* ~ "*/"
  | "//" ~ ANY+ ~ "\n"
}

LAMBDA = _{ "λ" | "\\" }
DOT = _{ "." }
OPEN_PAREN = _{ "(" }
CLOSE_PAREN = _{ ")" }

main = { SOI ~ term ~ EOI }

variable = @{ LETTER+ }
abstraction = { LAMBDA ~ variable ~ DOT ~ term }
application = {
  variable ~ term
  | OPEN_PAREN ~ term ~ CLOSE_PAREN ~ term
}

term = {
  application
  | abstraction
  | variable
  | OPEN_PAREN ~ term ~ CLOSE_PAREN
}
